// Configurazione per le tabelle del data explorer
export interface FieldConfig {
  type: "text" | "number" | "boolean" | "date" | "datetime" | "select" | "textarea" | "json"
  required?: boolean
  options?: string[] // Per campi select
  hidden?: boolean // Per nascondere campi dalla visualizzazione
  autoGenerated?: boolean // Per campi generati automaticamente
  readonly?: boolean // Per campi non modificabili
}

export interface TableConfig {
  fields: Record<string, FieldConfig>
  displayName: string
  description?: string
  primaryKey: string
  hiddenFields?: string[] // Campi da nascondere nella visualizzazione
}

export const TABLE_FIELDS: Record<string, TableConfig> = {
  todolist: {
    displayName: "Todo List",
    description: "Gestione delle attività e task",
    primaryKey: "id",
    hiddenFields: ["priorita"], // Nascondi il campo priorita come nel codice originale
    fields: {
      id: {
        type: "number",
        autoGenerated: true,
        readonly: true,
      },
      titolo: {
        type: "text",
        required: true,
      },
      descrizione: {
        type: "textarea",
      },
      stato: {
        type: "select",
        options: ["da_fare", "in_corso", "completato", "annullato"],
        required: true,
      },
      data_scadenza: {
        type: "date",
      },
      priorita: {
        type: "select",
        options: ["bassa", "media", "alta", "urgente"],
        hidden: true, // Campo nascosto
      },
      utente_id: {
        type: "number",
        required: true,
      },
      created_at: {
        type: "datetime",
        autoGenerated: true,
        readonly: true,
      },
      updated_at: {
        type: "datetime",
        autoGenerated: true,
        readonly: true,
      },
    },
  },
  utenti: {
    displayName: "Utenti",
    description: "Gestione degli utenti del sistema",
    primaryKey: "id",
    fields: {
      id: {
        type: "number",
        autoGenerated: true,
        readonly: true,
      },
      username: {
        type: "text",
        required: true,
      },
      email: {
        type: "text",
        required: true,
      },
      nome: {
        type: "text",
      },
      cognome: {
        type: "text",
      },
      ruolo: {
        type: "select",
        options: ["admin", "user", "guest"],
        required: true,
      },
      attivo: {
        type: "boolean",
      },
      ultimo_accesso: {
        type: "datetime",
        readonly: true,
      },
      data_creazione: {
        type: "datetime",
        autoGenerated: true,
        readonly: true,
      },
      password: {
        type: "text",
        hidden: true, // Campo nascosto per sicurezza
      },
    },
  },
  note: {
    displayName: "Note",
    description: "Gestione delle note personali",
    primaryKey: "id",
    fields: {
      id: {
        type: "number",
        autoGenerated: true,
        readonly: true,
      },
      titolo: {
        type: "text",
        required: true,
      },
      contenuto: {
        type: "textarea",
      },
      utente_id: {
        type: "number",
        required: true,
      },
      tags: {
        type: "json",
      },
      created_at: {
        type: "datetime",
        autoGenerated: true,
        readonly: true,
      },
      updated_at: {
        type: "datetime",
        autoGenerated: true,
        readonly: true,
      },
    },
  },
  pagine: {
    displayName: "Pagine",
    description: "Gestione delle pagine del sito",
    primaryKey: "id",
    fields: {
      id: {
        type: "number",
        autoGenerated: true,
        readonly: true,
      },
      titolo: {
        type: "text",
        required: true,
      },
      contenuto: {
        type: "textarea",
      },
      slug: {
        type: "text",
        required: true,
      },
      pubblicata: {
        type: "boolean",
      },
      utente_id: {
        type: "number",
        required: true,
      },
      metadata: {
        type: "json",
      },
      created_at: {
        type: "datetime",
        autoGenerated: true,
        readonly: true,
      },
      updated_at: {
        type: "datetime",
        autoGenerated: true,
        readonly: true,
      },
    },
  },
  temi: {
    displayName: "Temi",
    description: "Gestione dei temi dell'interfaccia",
    primaryKey: "id",
    fields: {
      id: {
        type: "number",
        autoGenerated: true,
        readonly: true,
      },
      nome: {
        type: "text",
        required: true,
      },
      descrizione: {
        type: "text",
      },
      css_variables: {
        type: "json",
        required: true,
      },
      attivo: {
        type: "boolean",
      },
      created_at: {
        type: "datetime",
        autoGenerated: true,
        readonly: true,
      },
      updated_at: {
        type: "datetime",
        autoGenerated: true,
        readonly: true,
      },
    },
  },
}

// Helper functions per lavorare con le configurazioni
export function getTableConfig(tableName: string): TableConfig | null {
  return TABLE_FIELDS[tableName] || null
}

export function getVisibleFields(tableName: string): string[] {
  const config = getTableConfig(tableName)
  if (!config) return []

  return Object.keys(config.fields).filter((fieldName) => {
    const field = config.fields[fieldName]
    const isHidden = field.hidden || config.hiddenFields?.includes(fieldName)
    return !isHidden
  })
}

export function getEditableFields(tableName: string): string[] {
  const config = getTableConfig(tableName)
  if (!config) return []

  return Object.keys(config.fields).filter((fieldName) => {
    const field = config.fields[fieldName]
    const isHidden = field.hidden || config.hiddenFields?.includes(fieldName)
    const isReadonly = field.readonly || field.autoGenerated
    return !isHidden && !isReadonly
  })
}

export function getFieldType(tableName: string, fieldName: string): string {
  const config = getTableConfig(tableName)
  if (!config || !config.fields[fieldName]) return "text"

  return config.fields[fieldName].type
}

export function getFieldOptions(tableName: string, fieldName: string): string[] {
  const config = getTableConfig(tableName)
  if (!config || !config.fields[fieldName]) return []

  return config.fields[fieldName].options || []
}

export function isFieldRequired(tableName: string, fieldName: string): boolean {
  const config = getTableConfig(tableName)
  if (!config || !config.fields[fieldName]) return false

  return config.fields[fieldName].required || false
}
