// Configurazione per le tabelle del data explorer
export interface FieldConfig {
  type: "text" | "number" | "boolean" | "date" | "datetime" | "select" | "textarea" | "json"
  required?: boolean
  options?: string[] // Per campi select
  autoGenerated?: boolean // Per campi auto-generati come ID, created_at, etc.
  hidden?: boolean // Per nascondere campi dalla visualizzazione
}

export interface TableConfig {
  displayName: string
  fields: Record<string, FieldConfig>
  primaryKey: string
  orderBy?: string
  searchFields?: string[]
}

export const TABLE_FIELDS: Record<string, TableConfig> = {
  todolist: {
    displayName: "Todo List",
    primaryKey: "id",
    orderBy: "created_at",
    searchFields: ["titolo", "descrizione"],
    fields: {
      id: {
        type: "number",
        autoGenerated: true,
        required: true,
      },
      titolo: {
        type: "text",
        required: true,
      },
      descrizione: {
        type: "textarea",
        required: false,
      },
      stato: {
        type: "select",
        options: ["da_fare", "in_corso", "completato"],
        required: true,
      },
      priorita: {
        type: "select",
        options: ["bassa", "media", "alta"],
        required: false,
        hidden: true, // Nascosto come richiesto nel codice originale
      },
      data_scadenza: {
        type: "date",
        required: false,
      },
      utente_id: {
        type: "number",
        required: true,
      },
      created_at: {
        type: "datetime",
        autoGenerated: true,
      },
      updated_at: {
        type: "datetime",
        autoGenerated: true,
      },
    },
  },
  utenti: {
    displayName: "Utenti",
    primaryKey: "id",
    orderBy: "nome",
    searchFields: ["nome", "username", "email"],
    fields: {
      id: {
        type: "number",
        autoGenerated: true,
        required: true,
      },
      nome: {
        type: "text",
        required: true,
      },
      username: {
        type: "text",
        required: true,
      },
      email: {
        type: "text",
        required: true,
      },
      ruolo: {
        type: "select",
        options: ["utente", "admin"],
        required: true,
      },
      created_at: {
        type: "datetime",
        autoGenerated: true,
      },
      updated_at: {
        type: "datetime",
        autoGenerated: true,
      },
    },
  },
  note: {
    displayName: "Note",
    primaryKey: "id",
    orderBy: "created_at",
    searchFields: ["titolo", "contenuto"],
    fields: {
      id: {
        type: "number",
        autoGenerated: true,
        required: true,
      },
      titolo: {
        type: "text",
        required: true,
      },
      contenuto: {
        type: "textarea",
        required: false,
      },
      utente_id: {
        type: "number",
        required: true,
      },
      created_at: {
        type: "datetime",
        autoGenerated: true,
      },
      updated_at: {
        type: "datetime",
        autoGenerated: true,
      },
    },
  },
  pagine: {
    displayName: "Pagine",
    primaryKey: "id",
    orderBy: "created_at",
    searchFields: ["titolo", "contenuto"],
    fields: {
      id: {
        type: "number",
        autoGenerated: true,
        required: true,
      },
      titolo: {
        type: "text",
        required: true,
      },
      contenuto: {
        type: "textarea",
        required: false,
      },
      slug: {
        type: "text",
        required: false,
      },
      pubblicata: {
        type: "boolean",
        required: true,
      },
      utente_id: {
        type: "number",
        required: true,
      },
      created_at: {
        type: "datetime",
        autoGenerated: true,
      },
      updated_at: {
        type: "datetime",
        autoGenerated: true,
      },
    },
  },
  temi: {
    displayName: "Temi",
    primaryKey: "id",
    orderBy: "nome_tema",
    searchFields: ["nome_tema"],
    fields: {
      id: {
        type: "number",
        autoGenerated: true,
        required: true,
      },
      nome_tema: {
        type: "text",
        required: true,
      },
      colore_titolo: {
        type: "text",
        required: false,
      },
      colore_sfondo: {
        type: "text",
        required: false,
      },
      colore_testo: {
        type: "text",
        required: false,
      },
      colore_accento: {
        type: "text",
        required: false,
      },
      carattere_tipo: {
        type: "text",
        required: false,
      },
      carattere_dimensione: {
        type: "number",
        required: false,
      },
      carattere_colore: {
        type: "text",
        required: false,
      },
      colore_header: {
        type: "text",
        required: false,
      },
      colore_footer: {
        type: "text",
        required: false,
      },
      colore_background: {
        type: "text",
        required: false,
      },
      colore_card: {
        type: "text",
        required: false,
      },
      colore_tabs: {
        type: "text",
        required: false,
      },
      colore_div: {
        type: "text",
        required: false,
      },
      border_radius: {
        type: "text",
        required: false,
      },
      css_variables: {
        type: "json",
        required: false,
      },
      created_at: {
        type: "datetime",
        autoGenerated: true,
      },
      updated_at: {
        type: "datetime",
        autoGenerated: true,
      },
    },
  },
}

// Funzione helper per ottenere la configurazione di una tabella
export function getTableConfig(tableName: string): TableConfig | null {
  return TABLE_FIELDS[tableName] || null
}

// Funzione helper per ottenere i campi visibili di una tabella
export function getVisibleFields(tableName: string): Record<string, FieldConfig> {
  const config = getTableConfig(tableName)
  if (!config) return {}

  return Object.fromEntries(Object.entries(config.fields).filter(([_, fieldConfig]) => !fieldConfig.hidden))
}

// Funzione helper per ottenere i campi editabili di una tabella
export function getEditableFields(tableName: string): Record<string, FieldConfig> {
  const config = getTableConfig(tableName)
  if (!config) return {}

  return Object.fromEntries(
    Object.entries(config.fields).filter(([_, fieldConfig]) => !fieldConfig.autoGenerated && !fieldConfig.hidden),
  )
}
